FROM mcr.microsoft.com/playwright/python:v1.40.0-jammy as build-image

ARG FUNCTION_DIR
COPY ./code .

COPY ./requirements.txt .

RUN pip install -r requirements.txt
RUN playwright install

CMD ["python3.10", "main.py"]