FROM mcr.microsoft.com/playwright/python:v1.40.0-jammy as build-image


ARG FUNCTION_DIR
COPY ./code .

COPY requirements.txt .

RUN pip install -r requirements.txt
RUN playwright install

ENV YEAR="2023" SEMESTER="2"
CMD ["uvicorn", "main:app","--host","127.0.0.1", "--port", "80"]







